### ISSUE TITLE
Persistent Store of data against a key and Cancel it using API call

### ISSUE THREAD

**Issue by rsdelhi91** [savoirfairelinux/opendht#429] opened 2019-09-01 11:28 UTC
Hi,

I am looking to see if it is possible to store data on the DHT network in a persistent manner and then deactivate its persistence using API calls? I can see that capability present in the interactive dhtnode utility but haven't seen so from an API call perspective.

**Comment by binarytrails** [comment] 2019-09-02 16:50
@rsdelhi91 the put signature has a param for it ```put(const InfoHash& id, Sp<Value> val, DoneCallback callback, time_point created, bool permanent)```, https://github.com/savoirfairelinux/opendht/blob/master/src/dht.cpp#L915

**Comment by linas** [comment] 2019-11-02 18:41
This seems to work, but behaves oddly.   I'd like to have data be either permanent, or have it be removed (as soon as possible).  To do this, I created a ` dht::ValueType` with an expiration of one second.  Then I `dht::DhtRunner::put()` it, with `permanent=true`.  That "sort-of" works.  It sort-of works, in that, on a peer node, I can see it in the storage log. However, on the peer node, the `dht::ValueType::StorePolicy()` callback triggers every second!    Yuck! 

Next, to delete the data, I did the `put()` again, with `permanent=false`.  That works. The `StorePolicy()` stops being called, and the storage log now shows zero bytes for the data.  Great!

Now I try to recreate the data. calling `put()` again, with `permanent=true`.  This "sort-of" does not work. It does reappear in the local storage log, but it never shows up in the peer, ever again... its not propagated.

Setting the expiration to 100 minutes ... well, the data of course sticks around for 100 minutes, even if its not permanent.

Of course, what I'm trying to do is to implement insert-delete semantics. The goal is to insert data, have it spread through the DHT, make it long-lived -- say a few days, or longer -- but then also have the ability to delete it - instantly, immediately, right away - and have that deletion propagate through the DHT. Then, later on (say minutes or hours later) I want to be able to create it again, and have it propagate.

Since the above didn't work as hoped-for, I tried a different work-around: to "delete" the data, I would `put()` a `dht::Value` with exactly the same `id` as before, but with truncated data.  This doesn't work at all, in a different way:  (1) sometimes the truncated data does not propagate out to peers, and (2) if it does propagate out to peers, then the peers will have *two* (or more) values: the original, and the truncated version. There does not seem to be any way to use `ValueType::StorePolicy()` or `ValueType::EditPolicy()` to drop the older value.

I really really would like to have this add/drop functionality; I'm willing to dive into the opendht code base to see if I can make it work, but would need architecture advice to do this ...

**Comment by aberaud** [comment] 2019-11-04 16:18
I will investigate various issues pointed out by @linas 

To answer the original question, there is a "proper" API to cancel a permanent put:
`cancelPut(InfoHash, Value::Id)`
or
`cancelPut(InfoHash, const shared_ptr<Value>&)`

**Comment by aberaud** [comment] 2019-11-04 18:28
@linas 
`Now I try to recreate the data. calling put() again, with permanent=true. This "sort-of" does not work. It does reappear in the local storage log, but it never shows up in the peer, ever again... its not propagated.`

Do you have some piece of code to reproduce this ? I tried to reproduce it but it worked fine (using custom OpenDHT with default value expiration of 1 min) :

```c++
#include <opendht.h>

#include <mutex>
#include <condition_variable>

const std::string KEY = "toto";
const std::string DATA = "42";

int main(int argc, char **argv)
{
    auto key = dht::InfoHash::get(KEY);
    auto val = std::make_shared<dht::Value>((const uint8_t*)DATA.data(), DATA.size());

    dht::DhtRunner::Config config;
    config.dht_config.node_config.network = 5;
    config.peer_discovery = true;
    config.peer_publish = true;

    std::mutex mtx;
    std::unique_lock<std::mutex> lk(mtx);
    std::condition_variable cv;

    dht::DhtRunner node;
    node.run((in_port_t)4222, config);
    //node.bootstrap("bootstrap.jami.net");

    // Waiting for the node to find other nodes on the same host or local network
    std::this_thread::sleep_for(std::chrono::seconds(2));

    // use the node...
    bool over = false;
    node.put(key, val, [&](bool ok) {
        std::lock_guard<std::mutex> l(mtx);
        over = true;
        cv.notify_all();
        std::cout << "Put done " << ok << std::endl;
    }, dht::time_point::max(), true);
    cv.wait(lk, [&]{ return over; });

    //std::this_thread::sleep_for(std::chrono::seconds(90));
    //node.cancelPut(key, val);
    std::this_thread::sleep_for(std::chrono::seconds(90));

    over = false;
    node.put(key, val, [&](bool ok) {
        std::lock_guard<std::mutex> l(mtx);
        over = true;
        cv.notify_all();
        std::cout << "Put2 done " << ok << std::endl;
    });
    cv.wait(lk, [&]{ return over; });

    std::this_thread::sleep_for(std::chrono::seconds(90));
    over = false;
    node.put(key, val, [&](bool ok) {
        std::lock_guard<std::mutex> l(mtx);
        over = true;
        cv.notify_all();
        std::cout << "Put3 done " << ok << std::endl;
    }, dht::time_point::max(), true);
    cv.wait(lk, [&]{ return over; });

    // stop the node
    over = false;
    node.shutdown([&]{
        std::lock_guard<std::mutex> l(mtx);
        over = true;
        cv.notify_all();
    });
    cv.wait(lk, [&]{ return over; });
    std::cout << "Shutdown done" << std::endl;
    return 0;
}
```

On a terminal on the same host:
```bash
$ dhtnode -D -n 5
OpenDHT node e9437f1b65325e5c15f955cf01e782151c759104 running on port 34836
 (type 'h' or 'help' for a list of possible commands)

>> l toto
Listen: found 1 values
	Value[id:34dd9b1a504bd98f Data (type: 0 ): 3432]
Listening, token: 1
>> Listen: found 1 values expired
	Value[id:34dd9b1a504bd98f Data (type: 0 ): 3432]
Listen: found 1 values
	Value[id:34dd9b1a504bd98f Data (type: 0 ): 3432]
Listen: found 1 values expired
	Value[id:34dd9b1a504bd98f Data (type: 0 ): 3432]
```

**Comment by linas** [comment] 2019-11-04 23:38
I realize now that my comments might be misleading, and I may have misunderstood what is happening. Just because I `put()` a value in a local node, that does not mean that it will automatically appear in the remote node. Since I was not listening for it, it was invalid of me to assume it will appear there.  

My test network consists of two nodes, and I was assuming that with such a small network, both nodes will synchronize and thus provide redundancy.  This does not happen.  (Newbie question: how can I ask for/force redundancy?  Where can I pose questions like this, so that I don't spam github?)

**Comment by ghenry** [comment] 2022-05-06 19:46
Still a requirement?  

Thanks.

**Comment by linas** [comment] 2022-05-09 20:51
I am no longer using opendht in any of my projects (opendht is great, I loved it, but the architecture I want doesn't require DHT's as the primary component.)

**Comment by ghenry** [comment] 2022-05-10 08:23
Thanks Linas. I'll close this now.

**Closed by ghenry** 2022-05-10 08:23 UTC
Labels: bug, enhancement, question, feature
